# Generated by Django 5.2.4 on 2025-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the metric, e.g., 'Meals Served'", max_length=100, unique=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='Numeric value of the impact')),
                ('icon_class', models.CharField(blank=True, help_text="Bootstrap icon class for display, e.g., 'bi-egg-fried'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Counter',
                'verbose_name_plural': 'Impact Counters',
            },
        ),
    ]
