# Generated by Django 5.2.4 on 2025-08-31 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_impactcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the milestone, e.g., '500 Meals Served'", max_length=200)),
                ('description', models.TextField(help_text='Brief description of the achievement')),
                ('date_achieved', models.DateField(auto_now_add=True, help_text='Date when milestone was achieved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: associate milestone with a project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='home.project')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones & Achievements',
                'ordering': ['-date_achieved'],
            },
        ),
    ]
