# Generated by Django 5.2.4 on 2025-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback_type', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('donor', 'Donor'), ('general', 'General')], max_length=20)),
                ('feedback_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐2 ⭐'), (3, '3 ⭐3 ⭐3 ⭐'), (4, '4 ⭐4 ⭐4 ⭐4 ⭐'), (5, '5 ⭐5 ⭐5 ⭐5 ⭐5 ⭐')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
