# Generated by Django 5.2.4 on 2025-08-31 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recurring', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('ewallet', 'E-Wallet (JazzCash/EasyPaisa)'), ('cash', 'Cash / Cheque')], max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='home.project')),
            ],
        ),
    ]
