# Generated by Django 5.2.4 on 2025-08-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=5),
        ),
        migrations.AlterField(
            model_name='impactcounter',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='impactcounter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='impactcounter',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date_achieved',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='home.project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
